### ISSUE TITLE
Potential negative value in the attempt to compute absolute value for 32-bit hashcode 

### ISSUE THREAD

**Issue by aleroot** [threadly/auroraArc#11]
Bad attempt to compute absolute value of signed 32-bit hashcode in new org.threadly.db.aurora.AuroraClusterMonitor$ClusterChecker(SubmitterScheduler, long, Set)

https://github.com/threadly/auroraArc/blob/34e7aae0f12de2c95aa1d7ef488fa2d95f88847d/src/main/java/org/threadly/db/aurora/AuroraClusterMonitor.java#L164

This code generates a hashcode and then computes the absolute value of that hashcode. If the hashcode is Integer.MIN_VALUE, then the result will be negative as well (since Math.abs(Integer.MIN_VALUE) == Integer.MIN_VALUE).

**Comment by lwahlmeier** [comment]
This could definitely be an issue, might be better to get rid of the abs and % and just do:

```java

    Math.floorMod(System.identityHashCode(monitor), checkIntervalMillis)

```

**Comment by jentfoo** [comment]
Yea, good spot.  It looks like `StripedLock` inside threadly has the same flaw as well.  I corrected this here in 72abb64 by converting to a `long`.

@lwahlmeier why do you think floorMod (which would still need and `abs` call on the result) would be better than what is provided in 72abb64?  I will wait to do it in threadly till we decide what we are doing here.

**Comment by lwahlmeier** [comment]
I am pretty sure floorMod is never negative, as long as the 2nd argument isnt.  I *think* it works just like c's "%"(mod) operator unlike java's "%" which is a remainder.  

Either works, I think floorMod is probably a little faster too, though only in java8.

**Comment by jentfoo** [comment]
I incorrectly read the javadocs, you are correct, the sign would be right.

I decided to go ahead and make a small JMH test for this to see which one is actually faster

```  private final int hashCode = System.identityHashCode(this);
  private final int mod = 500;
  
  @Benchmark
  public void abs() {
    long val = Math.abs((long)hashCode) % mod;
  }

  @Benchmark
  public void floorMod() {
    int val = Math.floorMod(hashCode, mod);
  }```

I actually expected floorMod to be faster as well, but it wasen't:
```Benchmark           Mode  Cnt           Score          Error  Units
ModTests.abs       thrpt   25  2095212917.437 ± 22893007.536  ops/s
ModTests.floorMod  thrpt   25  1576673104.996 ± 11151730.174  ops/s
```

Minor difference though once you consider error percents.  If we wanted the cleaner `floorMod` implementation I would not be against it in any way, but my vote is the barely wining long cast + abs.

**Comment by lwahlmeier** [comment]
That's interesting, it really does not matter to me though, just mostly hate java's % operator it has bit me a few times.

**Comment by jentfoo** [comment]
Fixed in threadly https://github.com/threadly/threadly/commit/743229c70ba11ded431cc9cd7501af31faeb1e0c

I am releasing a 5.9 patch release for this now.
